spring.application.name=springbootapplication

logging.level.org.springframework= trace

currency-service.url=http://dev.keertangoswami.com
currency-service.username= devusername
currency-service.key= devkey

home-service.url=http://dev.home.com
home-service.username=devhomeusername
home-service.key=devhomekey


#-------logging levels----
# trace, debug , info, warning, error , off
